server.port=8121
spring.threads.virtual.enabled=true
server.tomcat.max-threads=20
server.tomcat.min-spare-threads=2
server.connection-timeout=10000

tcp2jms.tcp.serializer.header-size=2
tcp2jms.tcp.serializer.max-message-size=65535
tcp2jms.tcp.local.port=9100
tcp2jms.tcp.read.timeout=30000
tcp2jms.tcp.max-connections=200
tcp2jms.tcp.remote.host=
tcp2jms.tcp.remote.port=0

tcp2jms.jms.connection.broker-url=failover:(tcp://activemq-1:61616,tcp://activemq-2:61616)?jms.prefetchPolicy.queuePrefetch=1&initialReconnectDelay=100&maxReconnectDelay=10000&maxReconnectAttempts=-1&randomize=false

tcp2jms.jms.destination.self=hsm-transparent-lb-inbound-2
tcp2jms.jms.destination.control=xenticate.control
tcp2jms.jms.destination.outbound=hsm.transparent.lb.in
tcp2jms.jms.destination.inbound=hsm.transparent.lb.reply

tcp2jms.jms.listener.inbound-control.max-concurrent-consumers=1
tcp2jms.jms.listener.inbound-request.concurrent-consumers=10
tcp2jms.jms.listener.inbound-request.max-concurrent-consumers=50
tcp2jms.jms.listener.inbound-response.concurrent-consumers=10
tcp2jms.jms.listener.inbound-response.max-concurrent-consumers=50
